version: '3'

services:
  aesm:
    image: cashmaney/aesm
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy

  sample:
    image: cashmaney/enigma-sgx-node
    depends_on:
      - aesm
    devices:
      - /dev/sgx
    volumes:
      - /tmp/aesmd:/var/run/aesmd
    stdin_open: true
    tty: true
    environment:
      - http_proxy
      - https_proxy