version: "3.9"
services:
  localsecret-1:
    image: "ghcr.io/scrtlabs/localsecret:v0.0.0"
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
      - "9091:9091"
      - "1317:1317"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sf http://localhost:26657/status | jq -e '.result.sync_info.latest_block_height | tonumber > 0'",
        ]
      interval: 5s
      timeout: 1s

  localsecret-2:
    image: "ghcr.io/scrtlabs/localsecret:v0.0.0"
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "36657:26657"
      - "36656:26656"
      - "9391:9091"
      - "9390:9090"
      - "3317:1317"
    environment:
      CHAINID: "secretdev-2"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sf http://localhost:26657/status | jq -e '.result.sync_info.latest_block_height | tonumber > 0'",
        ]
      interval: 5s
      timeout: 1s

  relayer:
    image: "hermes:v0.0.0"
    depends_on:
      localsecret-1:
        condition: service_healthy
      localsecret-2:
        condition: service_healthy
