name: golangci-lint
on:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Simulate go-bindata
        run: |
          echo '// Asset loads and returns the asset for the given name.
          // It returns an error if the asset could not be found or
          // could not be loaded.
          func Asset(name string) ([]byte, error) {
            cannonicalName := strings.ReplaceAll(name, "\\", "/")
            if f, ok := _bindata[cannonicalName]; ok {
              return f()
            }
            return nil, fmt.Errorf("Asset %s not found", name)
          }' >> ./x/registration/internal/types/reg_keys.go
      run: 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.53.2
